### ISSUE TITLE
Nuget version conflict when using Arcus messaging in Azure Functions v4 project

### ISSUE THREAD

**Issue by SamVanhoutte** [arcus-azure/arcus.messaging#310]
**Describe the bug**
I have an Isolated worker functions project (v4) and I want to add the message pump, like described in the docs: https://messaging.arcus-azure.net/Features/message-pumps/service-bus-azure-functions

However, when adding the packages `Arcus.Messaging.Pumps.ServiceBus` 1.2.0 or `Arcus.Messaging.Abstractions` 1.2.0 to the project, a Version conflict warning is given:

These are the logs from Rider
```
@ Installing Arcus.Messaging.Pumps.ServiceBus in Customer.Backend.Workers started
Running restore with 8 concurrent jobs.
Reading project file /Users/sam/git/Customer/backend/src/Customer.Backend.Workers/Customer.Backend.Workers.csproj.
Restoring packages for /Users/sam/git/Customer/backend/src/Customer.Backend.Workers/Customer.Backend.Workers.csproj...
Restoring packages for .NETCoreApp,Version=v5.0...
Resolving conflicts for net5.0...
Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.ServiceBus 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.Abstractions 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Detected package version outside of dependency constraint: Arcus.Messaging.Abstractions 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Version conflict detected for Microsoft.Extensions.Configuration.Binder. Install/reference Microsoft.Extensions.Configuration.Binder 5.0.0 directly to project Customer.Backend.Workers to resolve this issue. 
 Customer.Backend.Workers -> Microsoft.Azure.Functions.Worker 1.6.0 -> Microsoft.Extensions.Hosting 5.0.0 -> Microsoft.Extensions.Configuration.Binder (>= 5.0.0) 
 Customer.Backend.Workers -> Arcus.Messaging.Pumps.ServiceBus 1.2.0 -> Microsoft.Extensions.Configuration.Binder (>= 3.1.8 && < 5.0.0).
Checking compatibility of packages on net5.0.
All packages and projects are compatible with net5.0.
Package restore failed. Rolling back package changes for 'Customer.Backend.Workers'.
Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.ServiceBus 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Confi ... e. 
 Customer.Backend.Workers -> Microsoft.Azure.Functions.Worker 1.6.0 -> Microsoft.Extensions.Hosting 5.0.0 -> Microsoft.Extensions.Configuration.Binder (>= 5.0.0) 
 Customer.Backend.Workers -> Arcus.Messaging.Pumps.ServiceBus 1.2.0 -> Microsoft.Extensions.Configuration.Binder (>= 3.1.8 && < 5.0.0).

NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'Customer.Backend.Workers'.
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteBuildIntegratedProjectActionsAsync(BuildIntegratedNuGetProject buildIntegratedProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<>c__DisplayClass6_0.<<InstallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.InstallInternal(IProject project, String packageId, String packgeUserStr, NuGetFeedContext feedContext, Int32 nestedLevel, NuGetNotificationMode mode, NuGetOperationReporter reporter, Func`3 nativeInstall, NuGetProject givenNuGetProject)

Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.ServiceBus 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.Abstractions 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Detected package version outside of dependency constraint: Arcus.Messaging.Abstractions 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Configuration.Abstractions 5.0.0 was resolved.
Version conflict detected for Microsoft.Extensions.Configuration.Binder. Install/reference Microsoft.Extensions.Configuration.Binder 5.0.0 directly to project Customer.Backend.Workers to resolve this issue. 
 Customer.Backend.Workers -> Microsoft.Azure.Functions.Worker 1.6.0 -> Microsoft.Extensions.Hosting 5.0.0 -> Microsoft.Extensions.Configuration.Binder (>= 5.0.0) 
 Customer.Backend.Workers -> Arcus.Messaging.Pumps.ServiceBus 1.2.0 -> Microsoft.Extensions.Configuration.Binder (>= 3.1.8 && < 5.0.0).
@ Installing Arcus.Messaging.Pumps.ServiceBus in Customer.Backend.Workers finished (0.388 sec)
[Notification][Install] Install failed (project: Customer.Backend.Workers, package: Arcus.Messaging.Pumps.ServiceBus v1.2.0)
Package restore failed. Rolling back package changes for 'Customer.Backend.Workers'.
Detected package version outside of dependency constraint: Arcus.Messaging.Pumps.ServiceBus 1.2.0 requires Microsoft.Extensions.Configuration.Abstractions (>= 3.1.8 && < 5.0.0) but version Microsoft.Extensions.Confi ... e. 
 Customer.Backend.Workers -> Microsoft.Azure.Functions.Worker 1.6.0 -> Microsoft.Extensions.Hosting 5.0.0 -> Microsoft.Extensions.Configuration.Binder (>= 5.0.0) 
 Customer.Backend.Workers -> Arcus.Messaging.Pumps.ServiceBus 1.2.0 -> Microsoft.Extensions.Configuration.Binder (>= 3.1.8 && < 5.0.0).
```

**To Reproduce**
1. Create new functions project (version 4 - isolated worker - .NET 5)
2. Add package to the project (I am using Jetbrains Rider) with `Install-Package Arcus.Messaging.Pumps.ServiceBus -Version 1.2.0`
3. See exception

**Expected behavior**
Version conflicts would not happen

**Comment by stijnmoreels** [comment]
Thanks for mentioning!
Well, hmm, isolated functions is not something we already have investigated in. Currently, we only focus on in-process functions where the 'message pump' becomes the Service Bus trigger in the function, and you only need to register the message router.
This scenario, where you use a message pump in an Azure Function, that's not something we already worked about or explicitly support. The failure here shows that the packages used here are from our .NET Core variant, so I image that temporarily this could be fixed by targeting the project to .NET 6. I think this is more a 'bug' (maybe not even dat) for .NET 5 than for Azure Functions as 'not .NET 6' projects will have the load the .NET Core supported packages.

**Comment by stijnmoreels** [comment]
That's great news! Thx for the support! 🧡

**Comment by stijnmoreels** [comment]
Closing this as we publicly support .NET 6.
